steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean','build','jar','publish']
    env :
      - 'GITHUB_ACTOR=onkarpathak833'
      - 'REPO_TOKEN=c2d2fdf84ee8ca300cd95d1b79dabe00898fc61e'
    timeout: 600s
    artifacts:
      objects:
        location: 'gs://tw-onkar-data'
          paths: ['jars']
