steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean','build','jar','publish']
    env :
      - 'GITHUB_ACTOR=onkarpathak833'
      - 'REPO_TOKEN=c2d2fdf84ee8ca300cd95d1b79dabe00898fc61e'
    timeout: 600s
  - name : 'gcr.io/cloud-builders/docker'
    args: ['build','-t','gcr.io/project1-186407/spring-cassandra','.']
    env:
      - 'FILE_PATH=gs://tw-onkar-data/jars/spring-cassandra-1.0-SNAPSHOT.jar'

artifacts:
  objects:
    location: 'gs://tw-onkar-data/jars/'
    paths: ['/workspace/build/libs/spring-cassandra-1.0-SNAPSHOT.jar']
logsBucket: 'gs://tw-onkar-data/'
