steps:
  - name: 'gcr.io/cloud-builders/gradle'
    id : A
    entrypoint: bash
    args: ['./scripts/build.sh']
    volumes:
      - name : 'jar'
        path: '/jar'
    timeout: 600s

  - name : 'gcr.io/cloud-builders/docker'
    id : B
    waitFor:
      - A
    entrypoint: bash
    volumes:
      - name : 'jar'
        path: '/jar'
    args: ['./scripts/build_image.sh']

  - name: 'gcr.io/cloud-builders/docker'
    id : C
    waitFor:
      - B
    args: ['push','gcr.io/project1-186407/spring-cassandra']
    volumes:
      - name: 'jar'
        path: '/jar'

  - name: 'gcr.io/cloud-builders/gcloud'
    id : D
    waitFor:
      - C
    args: ['run', 'deploy', 'spring-cassandra', '--image', 'gcr.io/project1-186407/spring-cassandra:latest', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

logsBucket: 'gs://tw-onkar-data/'

artifacts:
  objects:
    location: 'gs://tw-onkar-data/jars/'
    paths: ['/workspace/build/libs/spring-cassandra-1.0-SNAPSHOT-application.jar']
